import 'package:get/get.dart';

class LocalizationString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English language
        'en_US': {
          "English": "English",
          "Login": "Login",
          "Signup": "Signup",
          "Forgot Password?": "Forgot Password",
          "Don't have an account?  ": "Don't have an account?  ",
          "Phone Number": "Phone Number",
          "Password": "Password",
          "Choose Language": "Choose Language",
          "Logged in successfully": "Logged in successfully",
          "Invalid phone number format": "Invalid phone number format",
          "Phone number is required": "Phone number is required",
          "Password must be at least 6 characters":
              "Password must be at least 6 characters",
          "Password is required": "Password is required",
          ////////////////////////login screen////////////////////////
          "Enter your details below to create your account and get started":
              "Enter your details below to create your account and get started",
          "Full Name": "Full Name",
          "Full name is required": "Full name is required",
          "Confirm Password": "Confirm Password",
          "Confirm password is required": "Confirm password is required",
          "Password does not match": "Password does not match",
          "Do you have an account?  ": "Do you have an account?  ",
          ////////////////////////////////////forgot password screen////////////////////////
          "Forgot Password": "Forgot Password",
          "Send OTP": "Send OTP",
          "Enter OTP": "Enter OTP",
          "We have sent an OTP to ": "We have sent an OTP to ",
          "Password changed successfuly": "Password changed successfuly",
          ///////////////////////////home screen////////////////////////
          "Hello ": "Hello ",
          "Good Morning!": "Good Morning!",
          "Good Afternoon!": "Good Afternoon!",
          "Good Evening!": "Good Evening!",
          "Something went wrong": "Something went wrong",
          "Very Poor": "Very Poor",
          "Poor": "Poor",
          "Average": "Average",
          "Good": "Good",
          "Excellent": "Excellent",
          "Your Credit Score: ": "Your Credit Score: ",
          "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!":
              "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!",
          "Your KYC is verified. A verified KYC helps improve your financial profile!":
              "Your KYC is verified. A verified KYC helps improve your financial profile!",
          "Loan App": "Loan App",
          "Please fill KYC before going to loan applications.":
              "Please fill KYC before going to loan applications.",
          "Verify": "Verify",
          "Provider": "Provider",
          "Provider Form": "Provider Form",
          "Murabaha": "Murabaha",
          "Musharaka": "Musharaka",
          "Mudarabah": "Mudarabah",
          "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.":
              "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.",
          "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.":
              "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.",
          "Mudarabah is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.":
              "Mudarabah is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.",
          "Collapse": "Collapse",
          "Expand": "Expand",
          //////////////////////////finances Screen////////////////////////
          "Finances": "Finances",
          "Loan Request": "Loan Request",
          "Loan Repay": "Loan Repay",
          "Loan Status": "Loan Status",
          "Add Provider": "Add Provider",
          "Overall loan History": "Overall loan History",
          "No active loans available": "No active loans available",
          ///////////////////////////////profile screen////////////////////////////
          "KYC Completed": "KYC Completed",
          "Complete KYC": "Complete KYC",
          "Personal Info.": "Personal Info.",
          "Business Info.": "Business Info.",
          "Images Info.": "Images Info.",
          "Account Info.": "Account Info.",
          "Add Business Partner": "Add Business Partner",
          "Completed Loans": "Completed Loans",
          "Pending Loans": "Pending Loans",
          "Failed Loans": "Failed Loans",
          "Click Here": "Click Here",
          "If you are here as a product seller and wanted to fill a form or check status please click the button bellow":
              "If you are here as a product seller and wanted to fill a form or check status please click the button bellow",
          "Home": "Home",
          "Profile": "Profile",
          "Confirm Logout": "Confirm Logout",
          "Do you want to Logout?": "Do you want to Logout?",
          "No": "No",
          "Yes": "Yes",
          "Error logging out": "Error logging out",
          ///////////////////////////////loan application screen////////////////////////////
          "This field is required": "This field is required",
          "Please enter a quantity": "Please enter a quantity",
          "Please enter a valid number": "Please enter a valid number",
          "Apply for Murabaha Loan": "Apply for Murabaha Loan",
          "No providers found": "No providers found",
          "Product request sent successfully":
              "Product request sent successfully",
          "Name of Product": "Name of Product",
          "Quantity of Asset": "Quantity of Asset",
          "Product Desc.": "Product Desc.",
          "Unit of Measurement": "Unit of Measurement",
          "Sector": "Sector",
          "Repayment Plan": "Repayment Plan",
          "Please add products first": "Please add products first",
          "Apply Loan": "Apply Loan",
          //////////////////////////////////////////kcy screen////////////////////////////
          "Bank Link": "Bank Link",
          "Pers. Info.": "Pers. Info.",
          "Bus. Info.": "Bus. Info.",
          "Upload Image": "Upload Image",
          "Rejected": "Rejected",
          "You can resubmit your KYC info. and we'll review it ASAP.":
              "You can resubmit your KYC info. and we'll review it ASAP.",
          "OK": "OK",
          "Your KYC submission is under review.":
              "Your KYC submission is under review.",
          "Pending": "Pending",
          "We will notify you once the review is complete.":
              "We will notify you once the review is complete.",
          "Success": "Success",
          "Your KYC submission has been approved.":
              "Your KYC submission has been approved.",
          "Thank you for completing your KYC process.":
              "Thank you for completing your KYC process.",
          "This field must be at least 13 digits long":
              "This field must be at least 13 digits long",
          "This field must be at least 6 digits long":
              "This field must be at least 6 digits long",
          "Account info. sent successfully": "Account info. sent successfully",
          "Account Verified Successfully": "Account Verified Successfully",
          "Complete all the fields below": "Complete all the fields below",
          "Bank Info.": "Bank Info.",
          "Account Number": "Account Number",
          "Submit": "Submit",
          "OTP": "OTP",
          "Add": "Add",
          "Please enter a valid name (letters and spaces only)":
              "Please enter a valid name (letters and spaces only)",
          "Name must be at least 2 characters long":
              "Name must be at least 2 characters long",
          "This field must be at least 2 characters long":
              "This field must be at least 2 characters long",
          "Personal info. sent successfully":
              "Personal info. sent successfully",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Id. Type": "Id. Type",
          "Driver's License": "Driver's License",
          "Passport": "Passport",
          "National ID": "National ID",
          "Date of Birth": "Date of Birth",
          "Education level": "Education level",
          "Primary": "Primary",
          "Secondary": "Secondary",
          "BSc.": "BSc.",
          "MSc.": "MSc.",
          "ID. No.": "ID. No.",
          "Marital Status": "Marital Status",
          "Single": "Single",
          "Married": "Married",
          "Divorced": "Divorced",
          "Widowed": "Widowed",
          "Spouse info.": "Spouse info.",
          "This field must contain only numbers":
              "This field must contain only numbers",
          "Altenative contact person": "Altenative contact person",
          "Residential Info.": "Residential Info.",
          "Region/ District": "Region/ District",
          "Zone/ Subcity": "Zone/ Subcity",
          "Woreda": "Woreda",
          "Kebele": "Kebele",
          "Re-Submit": "Re-Submit",
          "Business info. sent successfully":
              "Business info. sent successfully",
          "Business info fetched successfully":
              "Business info fetched successfully",
          "Business Name": "Business Name",
          "Website url (optional)": "Website url (optional)",
          "Tin No.": "Tin No.",
          "Business Type": "Business Type",
          "Small Business Trade": "Small Business Trade",
          "Manufacturing": "Manufacturing",
          "Agriculture": "Agriculture",
          "Transport": "Transport",
          "Hospitality": "Hospitality",
          "Halal Tourism": "Halal Tourism",
          "Technology": "Technology",
          "Building and Construction": "Building and Construction",
          "Education": "Education",
          "Other": "Other",
          "Year of Establishment": "Year of Establishment",
          "Ownership": "Ownership",
          "Sole": "Sole",
          "Partnership": "Partnership",
          "PLC": "PLC",
          "Cooperative": "Cooperative",
          "Finance Source": "Finance Source",
          "Own": "Own",
          "Family": "Family",
          "Fund": "Fund",
          "Loan": "Loan",
          "Business Level": "Business Level",
          "Startup": "Startup",
          "Growing": "Growing",
          "Advanced": "Advanced",
          "Starting Capital": "Starting Capital",
          "Current Capital": "Current Capital",
          "Starting Employee No.": "Starting Employee No.",
          "Current Employee No.": "Current Employee No.",
          "Annual Income(ETB)": "Annual Income(ETB)",
          "Business Address Info.": "Business Address Info.",
          "Please upload at least one image.":
              "Please upload at least one image.",
          "Images sent successfully!": "Images sent successfully!",
          "Upload the following files": "Upload the following files",
          "Personal and Business Info.": "Personal and Business Info.",
          "Renewed Id.": "Renewed Id.",
          "Renewed Id.(Sent)": "Renewed Id.(Sent)",
          "Renewed Trade License": "Renewed Trade License",
          "Renewed Trade License(Sent)": "Renewed Trade License(Sent)",
          "Commercial Registration Certificate":
              "Commercial Registration Certificate",
          "Commercial Registration Certificate(Sent)":
              "Commercial Registration Certificate(Sent)",
          "TIN No. (Applicant's)": "TIN No. (Applicant's)",
          "TIN No. (Applicant's)(Sent)": "TIN No. (Applicant's)(Sent)",
          "Selected: ": "Selected: ",
          ////////////////////////////business partner screen////////////////////////
          "Business Partne's Phone Number": "የንግድ አጋር ስልክ ቁጥር",
          "Verify Partner": "Verify Partner",
          "Partners Name": "Partners Name",
          "Partne's Phone Number": "Partne's Phone Number",
          "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions":
              "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions",
          "Add the phone number of the person to be registered":
              "Add the phone number of the person to be registered",
          "Close": "Close",
          "Register your Partner": "Register your Partner",
          "Business Partners": "Business Partners",
          "No Business Partners Found, Press the + button to add":
              "No Business Partners Found, Press the + button to add",
        },
        'am_ET': {
          "English": "አማርኛ",
          "Login": "ግባ",
          "Signup": "ተመዝገብ",
          "Forgot Password?": "የይለፍ ቃል ረሱ?",
          "Don't have an account?  ": "መለያ የለህም?",
          "Phone Number": "ስልክ ቁጥር",
          "Password": "የይለፍ ቃል",
          "Choose Language": "ቋንቋ ይምረጡ",
          "Logged in successfully": "በተሳካ ሁኔታ ገብቷል",
          "Invalid phone number format": "ልክ ያልሆነ የስልክ ቁጥር",
          "Phone number is required": "ስልክ ቁጥር ያስፈልጋል",
          "Password must be at least 6 characters":
              "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት",
          "Password is required": "የይለፍ ቃል ያስፈልጋል",
          ////////////////////////login screen////////////////////////
          "Enter your details below to create your account and get started":
              "መለያዎን ለመፍጠር እና ለመጀመር ዝርዝሮችዎን ከዚህ በታች ያስገቡ",
          "Full Name": "ሙሉ ስም",
          "Full name is required": "ሙሉ ስም ያስፈልጋል",
          "Confirm Password": "የይለፍ ቃል ያረጋግጡ",
          "Confirm password is required": "የይለፍ ቃል ማረጋግጫ ያስፈልጋል",
          "Password does not match": "የይለፍ ቃል አይዛመድም",
          "Do you have an account?  ": "መለያ የለህም?  ",
          ////////////////////////////forgot password screen////////////////////////
          "Forgot Password": "የይለፍ ቃል ረሱ",
          "Send OTP": "OTP ላክ",
          "Enter OTP": "OTP አስገባ",
          "We have sent an OTP to ": "OTP ልከናል ",
          "Password changed successfuly": "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል",
          ///////////////////////////home screen////////////////////////
          "Hello ": "ሰላም ",
          "Good Morning!": "እንደምን አነጉ!",
          "Good Afternoon!": "እንደምን አረፈዱ!",
          "Good Evening!": "አንደምን አመሹ!",
          "Something went wrong": "የሆነ ችግር ተፈጥሯል",
          "Very Poor": "በጣም ትንሽ",
          "Poor": "ትንሽ",
          "Average": "አማካይ",
          "Good": "ጥሩ",
          "Excellent": "እጅግ በጣም ጥሩ",
          "Your Credit Score: ": "የክሬዲት ነጥብዎ፡- ",
          "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!":
              "ጥሩ የብድር ነጥብ ለማግኘት የእርስዎን KYC ያጠናቅቁ። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Your KYC is verified. A verified KYC helps improve your financial profile!":
              "የእርስዎ KYC የተረጋገጠ ነጥብ ነው። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Loan App": "ብድር ማመልከቻ",

          "Please fill KYC before going to loan applications.":
              "ወደ ብድር ማመልከቻዎች ከመሄድዎ በፊት እባክዎን KYC ይሙሉ",
          "Verify": "ማንነትዎን ያረጋግጡ",
          "Provider": "አቅራቢ",
          "Provider Form": "የአቅራቢ ቅጽ",
          "Murabaha": "ሙራባሃ",
          "Musharaka": "ሙሻረካ",
          "Mudarabah": "ሙዳረባ",
          "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.":
              "ሙራባሃ በኮፕ ባንክ ሸሪዓን የሚያከብር የፋይናንስ ምርት ሲሆን ባንኩ ለደንበኞች እቃዎችን ገዝቶ በተገለጸለት ትርፍ እንደገና የሚሸጥበት ሲሆን ይህም ከወለድ ነፃ የሆነ ፋይናንስ በኢስላማዊ መርሆች መሰረት ይፈቅዳል።",
          "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.":
              "ሙሻራካ በሽርክና ላይ የተመሰረተ የፋይናንስ ዘዴ ሲሆን ባንኩም ሆነ ደንበኛው ለጋራ ወይም ለፕሮጀክት ካፒታል የሚያዋጡበት፣ ቀድሞ በተስማማው ጥምርታ መሠረት ትርፍ የሚካፈሉበት፣ ኪሳራው ደግሞ የሸሪዓን መርሆች በማክበር ከካፒታል መዋጮቸው ጋር በተመጣጣኝ መጠን የሚካፈሉበት ነው።",
          "Mudaraba is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.":
              "ሙዳርባ የትርፍ መጋራት ስምምነት አንዱ አካል (ባንኩ) ካፒታል ሲያቀርብ ሌላኛው አካል (ሥራ ፈጣሪው) ሥራውን የሚያስተዳድርበት፣ ቀደም ሲል በተስማማው ጥምርታ መሠረት ትርፍ የሚጋራበት እና በካፒታል አቅራቢው ብቻ የሚደርሰው ኪሳራ ነው። ከእስላማዊ የፋይናንስ ደንቦች ጋር ይጣጣማል።",
          "Collapse": "ሰብስብ",
          "Expand": "ዘርጋ",
          //////////////////////////finances Screen////////////////////////
          "Finances": "ፋይናንስ",
          "Loan Request": "የብድር መጠየቂያ",
          "Loan Repay": "የብድር ክፍያ",
          "Loan Status": "የብድር ሁኔታ",
          "Add Provider": "አቅራቢን ያክሉ",
          "Overall loan History": "አጠቃላይ የብድር ታሪክ",
          "No active loans available": "ምንም ገቢር ብድሮች የሉም",
          ///////////////////////////////profile screen////////////////////////////
          "KYC Completed": "የተጠናቀቀ KYC",
          "Complete KYC": "KYC ያጠናቅቁ",
          "Personal Info.": "የግል መረጃ",
          "Business Info.": "የንግድ መረጃ",
          "Images Info.": "የምስሎች መረጃ",
          "Account Info.": "የመለያ መረጃ",
          "Add Business Partner": "የንግድ አጋር ያክሉ",
          "Completed Loans": "የተጠናቀቁ ብድሮች",
          "Pending Loans": "በመጠባበቅ ላይ ያሉ ብድሮች",
          "Failed Loans": "ያልተሳኩ ብድሮች",
          "Click Here": "እዚህ ይሙሉ",
          "If you are here as a product seller and wanted to fill a form or check status please click the button bellow":
              "እዚህ እንደ ምርት ሻጭ ከሆኑ እና ፎርም መሙላት ከፈለጉ ወይም የብድር ሁኔታን ለማረጋገጥ እባክዎ ከታች ያለውን ቁልፍ ይጫኑ",
          "Home": "መነሻ",
          "Profile": "መገለጫ",
          "Confirm Logout": "መውጣት ያረጋግጡ",
          "Do you want to Logout?": "መውጣት ይፈልጋሉ?",
          "No": "አይ",
          "Yes": "አዎ",
          "Error logging out": "መውጣት ላይ ስህተት ተፈጥሯል",
          ///////////////////////////loan application screen////////////////////////
          "This field is required": "ይህ መረጃ ያስፈልጋል",
          "Please enter a quantity": "እባክዎ መጠን ያስገቡ",
          "Please enter a valid number": "እባክዎ ትክክለኛ ቁጥር ያስገቡ",
          "Apply for Murabaha Loan": "ለሙራባሃ ብድር ያመልክቱ",
          "No providers found": "ምንም አቅራቢዎች አልተገኙም",
          "Product request sent successfully": "የምርት ጥያቄ በተሳካ ሁኔታ ተልኳል",
          "Name of Product": "የምርት ስም",
          "Quantity of Asset": "የንብረት ብዛት",
          "Product Desc.": "የምርት መግለጫ",
          "Unit of Measurement": "የመለኪያ ክፍል",
          "Sector": "ዘርፍ",
          "Repayment Plan": "የመክፈያ እቅድ",
          "Please add products first": "እባክዎ መጀመሪያ ምርቶችን ያክሉ",
          "Apply Loan": "ብድር ያመልክቱ",
          ////////////////////////////////////kyc screen////////////////////////////
          "Bank Link": "አካውንት አገናኝ",
          "Pers. Info.": "የግል መረጃ",
          "Bus. Info.": "የንግድ መረጃ",
          "Upload Image": "ምስሎችን ያክሉ",
          "Rejected": "አልተሳካም",
          "You can resubmit your KYC info. and we'll review it ASAP.":
              "የእርስዎን የKYC መረጃ እንደገና ማስገባት ይችላሉ። እና በፍጥነት እንገመግመዋለን።",
          "OK": "እሺ",
          "Your KYC submission is under review.": "የእርስዎ KYC መረጃ በግምገማ ላይ ነው።",
          "Pending": "በመጠባበቅ ላይ",
          "We will notify you once the review is complete.":
              "ግምገማው እንደተጠናቀቀ እናሳውቅዎታለን።",
          "Success": "ተሳክቷል",
          "Your KYC submission has been approved.": "የKYC መረጃዎ ጸድቋል።",
          "Thank you for completing your KYC process.":
              "የKYC ሂደትዎን ስላጠናቀቁ እናመሰግናለን።",
          "This field must be at least 13 digits long":
              "ይህ መስክ ቢያንስ 13 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "This field must be at least 6 digits long":
              "ይህ መስክ ቢያንስ 6 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "Account info. sent successfully": "የአካውንት ቁጥር በተሳካ ሁኔታ ተልኳል",
          "Account Verified Successfully": "አካውንትዎ በተሳካ ሁኔታ ተረጋግጧል",
          "Complete all the fields below": "ከታች ያሉትን ሁሉንም መረጃዎች ያጠናቅቁ",
          "Bank Info.": "አካውንት መረጃ",
          "Account Number": "አካውንት ቁጥር",
          "Submit": "አስገባ",
          "OTP": "OTP",
          "Add": "አክል",
          "Please enter a valid name (letters and spaces only)":
              "እባክዎ ትክክለኛ ስም ያስገቡ (ፊደሎች እና ክፍተቶች ብቻ)",
          "Name must be at least 2 characters long": "ስም ቢያንስ 2 ፊድላት መሆን አለበት",
          "This field must be at least 2 characters long":
              "ይህ መስክ ቢያንስ የ2 ፊደላት ርዝመት ሊኖረው ይገባል።",
          "Personal info. sent successfully": "የግል መረጃ በተሳካ ሁኔታ ተልኳል።",
          "First Name": "ስም",
          "Last Name": "የአባት ስም",
          "Gender": "ጾታ",
          "Male": "ወንድ",
          "Female": "ሴት",
          "Id. Type": "መታወቂያ ዓይነት",
          "Driver's License": "የመንጃ ፍቃድ",
          "Passport": "ፓስፖርት",
          "National ID": "ብሔራዊ መታወቂያ",
          "Date of Birth": "የትውልድ ቀን",
          "Education level": "የትምህርት ደረጃ",
          "Primary": "መጀመሪያ ደረጃ",
          "Secondary": "ሁለተኛ ደረጃ",
          "BSc.": "ዲግሪ",
          "MSc.": "ማስተርስ",
          "ID. No.": "የመታወቂያ ቁጥር",
          "Marital Status": "የትዳር ሁኔታ",
          "Single": "ያላገባ",
          "Married": "ባለትዳር",
          "Divorced": "የተፋታ",
          "Widowed": "የሞተበት",
          "Spouse info.": "የትዳር አጋር መረጃ",
          "This field must contain only numbers": "ይህ መስክ ቁጥሮችን ብቻ መያዝ አለበት",
          "Altenative contact person": "የተያዥ ሰው መረጃ",
          "Residential Info.": "የመኖሪያ ቤት መረጃ",
          "Region/ District": "ክልል/ ከተማ",
          "Zone/ Subcity": "ዞን/ ክፍለ ከተማ",
          "Woreda": "ወረዳ",
          "Kebele": "ቀበሌ",
          "Re-Submit": "እንደገና አስገባ",
          "Business info. sent successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተልኳል",
          "Business info fetched successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተገኝቷል",
          "Business Name": "የንግድ ስም",
          "Website url (optional)": "ድህረገፅ (አማራጭ)",
          "Tin No.": "ቲን ቁጥር",
          "Business Type": "የንግድ ዓይነት",
          "Small Business Trade": "አነስተኛ የንግድ ልውውጥ",
          "Manufacturing": "ማምረት",
          "Agriculture": "ግብርና",
          "Transport": "መጓጓዣ",
          "Hospitality": "እንግዳ ተቀባይነት",
          "Halal Tourism": "ሃላል ቱሪዝም",
          "Technology": "ቴክኖሎጂ",
          "Building and Construction": "ግንባታ",
          "Education": "ትምህርት",
          "Other": "ሌላ",
          "Year of Establishment": "የተቋቋመበት ዓመት",
          "Ownership": "ባለቤትነት",
          "Sole": "የግል",
          "Partnership": "አጋርነት",
          "PLC": "ኃ.የተ.የግ.ማ",
          "Cooperative": "ህብረት",
          "Finance Source": "የፋይናንስ ምንጭ",
          "Own": "የራስ",
          "Family": "ቤተሰብ",
          "Fund": "ፈንድ",
          "Loan": "ብድር",
          "Business Level": "የንግድ ደረጃ",
          "Startup": "ጀማሪ",
          "Growing": "በማደግ ላይ",
          "Advanced": "የላቀ",
          "Starting Capital": "የመጀመሪያ ካፒታል",
          "Current Capital": "የአሁኑ ካፒታል",
          "Starting Employee No.": "የመጀመሪያ ሰራተኛ ቁጥር",
          "Current Employee No.": "የአሁኑ ሰራተኛ ቁጥር",
          "Annual Income(ETB)": "ዓመታዊ ገቢ (ብር)",
          "Business Address Info.": "የንግድ አድራሻ መረጃ",
          "Please upload at least one image.": "እባክዎ ቢያንስ አንድ ምስል ይላኩ።",
          "Images sent successfully!": "ምስሎች በተሳካ ሁኔታ ተልኳል!",
          "Upload the following files": "ከታች ያሉትን ምስሎች ያክሉ",
          "Personal and Business Info.": "የግል እና የንግድ መረጃ",
          "Renewed Id.": "የታደሰ መታወቂያ",
          "Renewed Id.(Sent)": "የታደሰ መታወቂያ(ተልኳል)",
          "Renewed Trade License": "የታደሰ የንግድ ፍቃድ",
          "Renewed Trade License(Sent)": "የታደሰ የንግድ ፍቃድ(ተልኳል)",
          "Commercial Registration Certificate": "የንግድ ምዝገባ የምስክር ወረቀት",
          "Commercial Registration Certificate(Sent)":
              "የንግድ ምዝገባ የምስክር ወረቀት(ተልኳል)",
          "TIN No. (Applicant's)": "ቲን ቁጥር (የአመልካች)",
          "TIN No. (Applicant's)(Sent)": "ቲን ቁጥር (የአመልካች)(ተልኳል)",
          "Selected: ": "ተመርጧል: ",
          ///////////////////////business partner screen////////////////////////
          "Business Partne's Phone Number": "የንግድ አጋር ስልክ ቁጥር",
          "Verify Partner": "የአጋር ማንነት ያረጋግጡ",
          "Partners Name": "የአጋር ስም",
          "Partne's Phone Number": "የአጋር ስልክ ቁጥር",
          "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions":
              "የንግድ አጋርዎ ያልተመዘገቡ ከሆነ በሚከተለው ሊንክ ወደ መድረኩ እንዲቀላቀሉ መጋበዝ ይችላሉ ወይም ሁሉንም KYC በመወከል የታችኛውን ቁልፍ በመጫን ወደ መድረኩ እንዲቀላቀሉ እና የብድር ጊዜውን እና ቅድመ ሁኔታዎችን እንዲቀበሉ ማድረግ ይችላሉ ",
          "Add the phone number of the person to be registered":
              "የሚመዘገበውን ሰው ስልክ ቁጥር አስገቡ",
          "Close": "ዝጋ",
          "Register your Partner": "አጋርዎን ይመዝግቡ",
          "Business Partners": "የንግድ አጋርዎች",
          "No Business Partners Found, Press the + button to add":
              "ምንም የንግድ አጋሮች አልተገኙም፣ ለመጨመር የ+ ቁልፍን ተጫን",
        },
        'or_ET': {
          "English": "Afaan Oromoo",
        }
      };
}
