import 'package:get/get.dart';

class LocalizationString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // English language
        'en_US': {
          "Michu Mizan": "Michu Mizan",
          "Welcome to": "Welcome to",
          "English": "English",
          "Login": "Login",
          "Signup": "Signup",
          "Forgot Password?": "Forgot Password",
          "Don't have an account?  ": "Don't have an account?  ",
          "Phone Number": "Phone Number",
          "Password": "Password",
          "Choose Language": "Choose Language",
          "Logged in successfully": "Logged in successfully",
          "Invalid phone number format": "Invalid phone number format",
          "Phone number is required": "Phone number is required",
          "Password must be at least 6 characters":
              "Password must be at least 6 characters",
          "Password is required": "Password is required",
          ////////////////////////login screen////////////////////////
          "Enter your details below to create your account and get started":
              "Enter your details below to create your account and get started",
          "Full Name": "Full Name",
          "Full name is required": "Full name is required",
          "Confirm Password": "Confirm Password",
          "Confirm password is required": "Confirm password is required",
          "Password does not match": "Password does not match",
          "Do you have an account?  ": "Do you have an account?  ",
          ////////////////////////////////////forgot password screen////////////////////////
          "Forgot Password": "Forgot Password",
          "Send OTP": "Send OTP",
          "Enter OTP": "Enter OTP",
          "We have sent an OTP to ": "We have sent an OTP to ",
          "Password changed successfuly": "Password changed successfuly",
          ///////////////////////////home screen////////////////////////
          "Hello ": "Hello ",
          "Good Morning!": "Good Morning!",
          "Good Afternoon!": "Good Afternoon!",
          "Good Evening!": "Good Evening!",
          "Something went wrong": "Something went wrong",
          "Very Poor": "Very Poor",
          "Poor": "Poor",
          "Average": "Average",
          "Good": "Good",
          "Excellent": "Excellent",
          "Your Credit Score: ": "Your Credit Score: ",
          "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!":
              "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!",
          "Your KYC is verified. A verified KYC helps improve your financial profile!":
              "Your KYC is verified. A verified KYC helps improve your financial profile!",
          "Loan App": "Loan App",
          "Please fill KYC before going to loan applications.":
              "Please fill KYC before going to loan applications.",
          "Verify": "Verify",
          "Provider": "Provider",
          "Provider Form": "Provider Form",
          "Murabaha": "Murabaha",
          "Musharaka": "Musharaka",
          "Mudarabah": "Mudarabah",
          "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.":
              "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.",
          "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.":
              "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.",
          "Mudarabah is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.":
              "Mudarabah is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.",
          "Collapse": "Collapse",
          "Expand": "Expand",
          //////////////////////////finances Screen////////////////////////
          "Finances": "Finances",
          "Loan Request": "Loan Request",
          "Loan Repay": "Loan Repay",
          "Loan Status": "Loan Status",
          "Add Provider": "Add Provider",
          "Overall loan History": "Overall loan History",
          "No active loans available": "No active loans available",
          ///////////////////////////////profile screen////////////////////////////
          "KYC Completed": "KYC Completed",
          "Complete KYC": "Complete KYC",
          "Personal Info.": "Personal Info.",
          "Business Info.": "Business Info.",
          "Images Info.": "Images Info.",
          "Account Info.": "Account Info.",
          "Add Business Partner": "Add Business Partner",
          "Completed Loans": "Completed Loans",
          "Pending Loans": "Pending Loans",
          "Failed Loans": "Failed Loans",
          "Click Here": "Click Here",
          "If you are here as a product seller and wanted to fill a form or check status please click the button bellow":
              "If you are here as a product seller and wanted to fill a form or check status please click the button bellow",
          "Home": "Home",
          "Profile": "Profile",
          "Confirm Logout": "Confirm Logout",
          "Do you want to Logout?": "Do you want to Logout?",
          "No": "No",
          "Yes": "Yes",
          "Error logging out": "Error logging out",
          ///////////////////////////////loan application screen////////////////////////////
          "This field is required": "This field is required",
          "Please enter a quantity": "Please enter a quantity",
          "Please enter a valid number": "Please enter a valid number",
          "Apply for Murabaha Loan": "Apply for Murabaha Loan",
          "No providers found": "No providers found",
          "Product request sent successfully":
              "Product request sent successfully",
          "Name of Product": "Name of Product",
          "Quantity of Asset": "Quantity of Asset",
          "Product Desc.": "Product Desc.",
          "Unit of Measurement": "Unit of Measurement",
          "Sector": "Sector",
          "Repayment Plan": "Repayment Plan",
          "Please add products first": "Please add products first",
          "Apply Loan": "Apply Loan",
          //////////////////////////////////////////kcy screen////////////////////////////
          "Bank Link": "Bank Link",
          "Pers. Info.": "Pers. Info.",
          "Bus. Info.": "Bus. Info.",
          "Upload Image": "Upload Image",
          "Rejected": "Rejected",
          "You can resubmit your KYC info. and we'll review it ASAP.":
              "You can resubmit your KYC info. and we'll review it ASAP.",
          "OK": "OK",
          "Your KYC submission is under review.":
              "Your KYC submission is under review.",
          "Pending": "Pending",
          "We will notify you once the review is complete.":
              "We will notify you once the review is complete.",
          "Success": "Success",
          "Your KYC submission has been approved.":
              "Your KYC submission has been approved.",
          "Thank you for completing your KYC process.":
              "Thank you for completing your KYC process.",
          "This field must be at least 13 digits long":
              "This field must be at least 13 digits long",
          "This field must be at least 6 digits long":
              "This field must be at least 6 digits long",
          "Account info. sent successfully": "Account info. sent successfully",
          "Account Verified Successfully": "Account Verified Successfully",
          "Complete all the fields below": "Complete all the fields below",
          "Bank Info.": "Bank Info.",
          "Account Number": "Account Number",
          "Submit": "Submit",
          "OTP": "OTP",
          "Add": "Add",
          "Please enter a valid name (letters and spaces only)":
              "Please enter a valid name (letters and spaces only)",
          "Name must be at least 2 characters long":
              "Name must be at least 2 characters long",
          "This field must be at least 2 characters long":
              "This field must be at least 2 characters long",
          "Personal info. sent successfully":
              "Personal info. sent successfully",
          "First Name": "First Name",
          "Last Name": "Last Name",
          "Gender": "Gender",
          "Male": "Male",
          "Female": "Female",
          "Id. Type": "Id. Type",
          "Driver's License": "Driver's License",
          "Passport": "Passport",
          "National ID": "National ID",
          "Date of Birth": "Date of Birth",
          "Education level": "Education level",
          "Primary": "Primary",
          "Secondary": "Secondary",
          "BSc.": "BSc.",
          "MSc.": "MSc.",
          "ID. No.": "ID. No.",
          "Marital Status": "Marital Status",
          "Single": "Single",
          "Married": "Married",
          "Divorced": "Divorced",
          "Widowed": "Widowed",
          "Spouse info.": "Spouse info.",
          "This field must contain only numbers":
              "This field must contain only numbers",
          "Altenative contact person": "Altenative contact person",
          "Residential Info.": "Residential Info.",
          "Region/ District": "Region/ District",
          "Zone/ Subcity": "Zone/ Subcity",
          "Woreda": "Woreda",
          "Kebele": "Kebele",
          "Re-Submit": "Re-Submit",
          "Business info. sent successfully":
              "Business info. sent successfully",
          "Business info fetched successfully":
              "Business info fetched successfully",
          "Business Name": "Business Name",
          "Website url (optional)": "Website url (optional)",
          "Tin No.": "Tin No.",
          "Business Type": "Business Type",
          "Small Business Trade": "Small Business Trade",
          "Manufacturing": "Manufacturing",
          "Agriculture": "Agriculture",
          "Transport": "Transport",
          "Hospitality": "Hospitality",
          "Halal Tourism": "Halal Tourism",
          "Technology": "Technology",
          "Building and Construction": "Building and Construction",
          "Education": "Education",
          "Other": "Other",
          "Year of Establishment": "Year of Establishment",
          "Ownership": "Ownership",
          "Sole": "Sole",
          "Partnership": "Partnership",
          "PLC": "PLC",
          "Cooperative": "Cooperative",
          "Finance Source": "Finance Source",
          "Own": "Own",
          "Family": "Family",
          "Fund": "Fund",
          "Loan": "Loan",
          "Business Level": "Business Level",
          "Startup": "Startup",
          "Growing": "Growing",
          "Advanced": "Advanced",
          "Starting Capital": "Starting Capital",
          "Current Capital": "Current Capital",
          "Starting Employee No.": "Starting Employee No.",
          "Current Employee No.": "Current Employee No.",
          "Annual Income(ETB)": "Annual Income(ETB)",
          "Business Address Info.": "Business Address Info.",
          "Please upload at least one image.":
              "Please upload at least one image.",
          "Images sent successfully!": "Images sent successfully!",
          "Upload the following files": "Upload the following files",
          "Personal and Business Info.": "Personal and Business Info.",
          "Renewed Id.": "Renewed Id.",
          "Renewed Id.(Sent)": "Renewed Id.(Sent)",
          "Renewed Trade License": "Renewed Trade License",
          "Renewed Trade License(Sent)": "Renewed Trade License(Sent)",
          "Commercial Registration Certificate":
              "Commercial Registration Certificate",
          "Commercial Registration Certificate(Sent)":
              "Commercial Registration Certificate(Sent)",
          "TIN No. (Applicant's)": "TIN No. (Applicant's)",
          "TIN No. (Applicant's)(Sent)": "TIN No. (Applicant's)(Sent)",
          "Selected: ": "Selected: ",
          ////////////////////////////business partner screen////////////////////////
          "Business Partner's Phone Number": "Business Partner's Phone Number",
          "Verify Partner": "Verify Partner",
          "Partners Name": "Partners Name",
          "Partne's Phone Number": "Partne's Phone Number",
          "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions":
              "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions",
          "Add the phone number of the person to be registered":
              "Add the phone number of the person to be registered",
          "Close": "Close",
          "Register your Partner": "Register your Partner",
          "Business Partners": "Business Partners",
          "No Business Partners Found, Press the + button to add":
              "No Business Partners Found, Press the + button to add",
          ////////////////////////////provider loan list screen////////////////////////
          "Provider Loan Lists": "Provider Loan Lists",
          "Fill a Form": "Fill a Form",
          "New": "New",
          "All": "All",
          "Approved": "Approved",
          "The loan application is pending approval from the customer":
              "The loan application is pending approval from the customer",
          "The loan application is under review by the Bank officers":
              "The loan application is under review by the Bank officers",
          "The loan application is rejected":
              "The loan application is rejected",
          "The loan application is under taking":
              "The loan application is under taking",
          "Agreements Accepted": "Agreements Accepted",
          "The loan application is now closed.":
              "The loan application is now closed.",
          "There are no loans found": "There are no loans found",
          "Name": "Name",
          "Desc.": "Desc.",
          "Qnt.": "Qnt.",
          "Price": "Price",
          "Remove Product": "Remove Product",
          "Are you sure you want to remove ":
              "Are you sure you want to remove ",
          "Cancel": "Cancel",
          "Remove": "Remove",
          "Unit of measurement": "Unit of measurement",
          "Description": "Description",
          "Quantity": "Quantity",
          "Under Review": "Under Review",
          "Please enter the individual price for each product":
              "Please enter the individual price for each product",
          "Product Owner Form": "Product Owner Form",
          "Total Price: ": "Total Price: ",
          "Price Expiration Date": "Price Expiration Date",
          "Please select a price expiration date":
              "Please select a price expiration date",
          "Please fill in all product prices":
              "Please fill in all product prices",
          "Confirm Submit": "Confirm Submit",
          "Confirm Reject": "Confirm Reject",
          "Are you sure you want to submit this request?":
              "Are you sure you want to submit this request?",
          "Are you sure you want to reject this request?":
              "Are you sure you want to reject this request?",
          ////////////////////////////Loan List Screen//////////////////////////
          "Loan Requests": "Loan Requests",
          "Congratulations!": "Congratulations!",
          "Your loan has been approved!": "Your loan has been approved!",
          "Your loan application has been successfully approved. You will be contacted shortly by our team for the next steps.":
              "Your loan application has been successfully approved. You will be contacted shortly by our team for the next steps.",
          "ETB ": "ETB ",
          "Back to Home": "Back to Home",
          "No products found": "No products found",
          "Loan Approval Status": "Loan Approval Status",
          "This loan application has been approved by the product owner and now it is under review by the bank's officials. The bank will put it's benefits to the product and will let you know the final offer soon.":
              "This loan application has been approved by the product owner and now it is under review by the bank's officials. The bank will put it's benefits to the product and will let you know the final offer soon.",
          "Total Price": "Total Price",
          "Confirmation": "Confirmation",
          "Are you sure you want to resubmit your new offer?":
              "Are you sure you want to resubmit your new offer?",
          "Are you sure you want to reject the offer?":
              "Are you sure you want to reject the offer?",
          "Accept Offer": "Accept Offer",
          "Resubmit Offer": "Resubmit Offer",
          "Reject Offer": "Reject Offer",
          "Murabaha Agreement": "Murabaha Agreement",
          "This loan application has been approved by the product owner and the bank officials.":
              "This loan application has been approved by the product owner and the bank officials.",
          "The total price as the owner gives is ":
              "The total price as the owner gives is ",
          " in ": " in ",
          "repayment duration.": "repayment duration.",
          ", then the bank has added its benefits to the product price, making the final offer ":
              ", then the bank has added its benefits to the product price, making the final offer ",
          "Now, you must accept this offer and pick your product from the owner as soon as possible.":
              "Now, you must accept this offer and pick your product from the owner as soon as possible.",
          "Pick your product": "Pick your product",
          "Are you sure you are ready to pick your product?":
              "Are you sure you are ready to pick your product?",
          "Please ensure you are at the product pickup location and ready to sign the Murabaha agreement.":
              "Please ensure you are at the product pickup location and ready to sign the Murabaha agreement.",
          "Not Ready": "Not Ready",
          "I'm Ready": "I'm Ready",
          "Promise to Purchase Agreement": "Promise to Purchase Agreement",
          "Agree": "Agree",
          "PDF saved": "PDF saved",
          "Failed to download PDF": "Failed to download PDF",
          "Failed to load PDF": "Failed to load PDF",
          "Reject": "Reject",
          "Accept": "Accept",
          "Duration of Financing": "Duration of Financing",
          "Total Murabaha Price": "Total Murabaha Price",
          "Mark up": "Mark up",
          "Purchase Cost": "Purchase Cost",
          "Processing Fees": "Processing Fees",
          "Product Name: ": "Product Name: ",
          "Unit Price: ": "Unit Price: ",
          "Quantity: ": "Quantity: ",
          "Total: ": "Total: ",
          "Edit Quantity": "Edit Quantity",
          "Delete Product": "Delete Product",
          "Are you sure you want to delete ":
              "Are you sure you want to delete ",
          "Save": "Save",
          "Delete": "Delete",
          "The loan application is pending approval from the merchant":
              "The loan application is pending approval from the merchant",
          "The loan application is approved and will be fulfilled once the product owner confirms it.":
              "The loan application is approved and will be fulfilled once the product owner confirms it.",
        },
        'am_ET': {
          "Michu Mizan": "ምቹ ሚዛን",
          "Welcome to": "እንኳን ደህና መጡ",
          "English": "አማርኛ",
          "Login": "ይግቡ",
          "Signup": "ተመዝገብ",
          "Forgot Password?": "የይለፍ ቃል ረሱ?",
          "Don't have an account?  ": "መለያ የለህም?",
          "Phone Number": "ስልክ ቁጥር",
          "Password": "የይለፍ ቃል",
          "Choose Language": "ቋንቋ ይምረጡ",
          "Logged in successfully": "በተሳካ ሁኔታ ገብቷል",
          "Invalid phone number format": "ልክ ያልሆነ የስልክ ቁጥር",
          "Phone number is required": "ስልክ ቁጥር ያስፈልጋል",
          "Password must be at least 6 characters":
              "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት",
          "Password is required": "የይለፍ ቃል ያስፈልጋል",
          ////////////////////////login screen////////////////////////
          "Enter your details below to create your account and get started":
              "መለያዎን ለመፍጠር እና ለመጀመር ዝርዝሮችዎን ከዚህ በታች ያስገቡ",
          "Full Name": "ሙሉ ስም",
          "Full name is required": "ሙሉ ስም ያስፈልጋል",
          "Confirm Password": "የይለፍ ቃል ያረጋግጡ",
          "Confirm password is required": "የይለፍ ቃል ማረጋግጫ ያስፈልጋል",
          "Password does not match": "የይለፍ ቃል አይዛመድም",
          "Do you have an account?  ": "መለያ የለህም?  ",
          ////////////////////////////forgot password screen////////////////////////
          "Forgot Password": "የይለፍ ቃል ረሱ",
          "Send OTP": "OTP ላክ",
          "Enter OTP": "OTP አስገባ",
          "We have sent an OTP to ": "OTP ልከናል ",
          "Password changed successfuly": "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል",
          ///////////////////////////home screen////////////////////////
          "Hello ": "ሰላም ",
          "Good Morning!": "እንደምን አነጉ!",
          "Good Afternoon!": "እንደምን አረፈዱ!",
          "Good Evening!": "አንደምን አመሹ!",
          "Something went wrong": "የሆነ ችግር ተፈጥሯል",
          "Very Poor": "በጣም ትንሽ",
          "Poor": "ትንሽ",
          "Average": "አማካይ",
          "Good": "ጥሩ",
          "Excellent": "እጅግ በጣም ጥሩ",
          "Your Credit Score: ": "የክሬዲት ነጥብዎ፡- ",
          "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!":
              "ጥሩ የብድር ነጥብ ለማግኘት የእርስዎን KYC ያጠናቅቁ። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Your KYC is verified. A verified KYC helps improve your financial profile!":
              "የእርስዎ KYC የተረጋገጠ ነጥብ ነው። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Loan App": "ብድር ማመልከቻ",

          "Please fill KYC before going to loan applications.":
              "ወደ ብድር ማመልከቻዎች ከመሄድዎ በፊት እባክዎን KYC ይሙሉ",
          "Verify": "ማንነትዎን ያረጋግጡ",
          "Provider": "አቅራቢ",
          "Provider Form": "የአቅራቢ ቅጽ",
          "Murabaha": "ሙራባሃ",
          "Musharaka": "ሙሻረካ",
          "Mudarabah": "ሙዳረባ",
          "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.":
              "ሙራባሃ በኮፕ ባንክ ሸሪዓን የሚያከብር የፋይናንስ ምርት ሲሆን ባንኩ ለደንበኞች እቃዎችን ገዝቶ በተገለጸለት ትርፍ እንደገና የሚሸጥበት ሲሆን ይህም ከወለድ ነፃ የሆነ ፋይናንስ በኢስላማዊ መርሆች መሰረት ይፈቅዳል።",
          "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.":
              "ሙሻራካ በሽርክና ላይ የተመሰረተ የፋይናንስ ዘዴ ሲሆን ባንኩም ሆነ ደንበኛው ለጋራ ወይም ለፕሮጀክት ካፒታል የሚያዋጡበት፣ ቀድሞ በተስማማው ጥምርታ መሠረት ትርፍ የሚካፈሉበት፣ ኪሳራው ደግሞ የሸሪዓን መርሆች በማክበር ከካፒታል መዋጮቸው ጋር በተመጣጣኝ መጠን የሚካፈሉበት ነው።",
          "Mudaraba is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.":
              "ሙዳርባ የትርፍ መጋራት ስምምነት አንዱ አካል (ባንኩ) ካፒታል ሲያቀርብ ሌላኛው አካል (ሥራ ፈጣሪው) ሥራውን የሚያስተዳድርበት፣ ቀደም ሲል በተስማማው ጥምርታ መሠረት ትርፍ የሚጋራበት እና በካፒታል አቅራቢው ብቻ የሚደርሰው ኪሳራ ነው። ከእስላማዊ የፋይናንስ ደንቦች ጋር ይጣጣማል።",
          "Collapse": "ሰብስብ",
          "Expand": "ዘርጋ",
          //////////////////////////finances Screen////////////////////////
          "Finances": "ፋይናንስ",
          "Loan Request": "የብድር መጠየቂያ",
          "Loan Repay": "የብድር ክፍያ",
          "Loan Status": "የብድር ሁኔታ",
          "Add Provider": "አቅራቢን ያክሉ",
          "Overall loan History": "አጠቃላይ የብድር ታሪክ",
          "No active loans available": "ምንም ገቢር ብድሮች የሉም",
          ///////////////////////////////profile screen////////////////////////////
          "KYC Completed": "የተጠናቀቀ KYC",
          "Complete KYC": "KYC ያጠናቅቁ",
          "Personal Info.": "የግል መረጃ",
          "Business Info.": "የንግድ መረጃ",
          "Images Info.": "የምስሎች መረጃ",
          "Account Info.": "የመለያ መረጃ",
          "Add Business Partner": "የንግድ አጋር ያክሉ",
          "Completed Loans": "የተጠናቀቁ ብድሮች",
          "Pending Loans": "በመጠባበቅ ላይ ያሉ ብድሮች",
          "Failed Loans": "ያልተሳኩ ብድሮች",
          "Click Here": "እዚህ ይሙሉ",
          "If you are here as a product seller and wanted to fill a form or check status please click the button bellow":
              "እዚህ እንደ ምርት ሻጭ ከሆኑ እና ፎርም መሙላት ከፈለጉ ወይም የብድር ሁኔታን ለማረጋገጥ እባክዎ ከታች ያለውን ቁልፍ ይጫኑ",
          "Home": "መነሻ",
          "Profile": "መገለጫ",
          "Confirm Logout": "መውጣት ያረጋግጡ",
          "Do you want to Logout?": "መውጣት ይፈልጋሉ?",
          "No": "አይ",
          "Yes": "አዎ",
          "Error logging out": "መውጣት ላይ ስህተት ተፈጥሯል",
          ///////////////////////////loan application screen////////////////////////
          "This field is required": "ይህ መረጃ ያስፈልጋል",
          "Please enter a quantity": "እባክዎ መጠን ያስገቡ",
          "Please enter a valid number": "እባክዎ ትክክለኛ ቁጥር ያስገቡ",
          "Apply for Murabaha Loan": "ለሙራባሃ ብድር ያመልክቱ",
          "No providers found": "ምንም አቅራቢዎች አልተገኙም",
          "Product request sent successfully": "የምርት ጥያቄ በተሳካ ሁኔታ ተልኳል",
          "Name of Product": "የምርት ስም",
          "Quantity of Asset": "የንብረት ብዛት",
          "Product Desc.": "የምርት መግለጫ",
          "Unit of Measurement": "የመለኪያ ክፍል",
          "Sector": "ዘርፍ",
          "Repayment Plan": "የመክፈያ እቅድ",
          "Please add products first": "እባክዎ መጀመሪያ ምርቶችን ያክሉ",
          "Apply Loan": "ብድር ያመልክቱ",
          ////////////////////////////////////kyc screen////////////////////////////
          "Bank Link": "አካውንት አገናኝ",
          "Pers. Info.": "የግል መረጃ",
          "Bus. Info.": "የንግድ መረጃ",
          "Upload Image": "ምስሎችን ያክሉ",
          "Rejected": "አልተሳካም",
          "You can resubmit your KYC info. and we'll review it ASAP.":
              "የእርስዎን የKYC መረጃ እንደገና ማስገባት ይችላሉ። እና በፍጥነት እንገመግመዋለን።",
          "OK": "እሺ",
          "Your KYC submission is under review.": "የእርስዎ KYC መረጃ በግምገማ ላይ ነው።",
          "Pending": "በመጠባበቅ ላይ",
          "We will notify you once the review is complete.":
              "ግምገማው እንደተጠናቀቀ እናሳውቅዎታለን።",
          "Success": "ተሳክቷል",
          "Your KYC submission has been approved.": "የKYC መረጃዎ ጸድቋል።",
          "Thank you for completing your KYC process.":
              "የKYC ሂደትዎን ስላጠናቀቁ እናመሰግናለን።",
          "This field must be at least 13 digits long":
              "ይህ መስክ ቢያንስ 13 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "This field must be at least 6 digits long":
              "ይህ መስክ ቢያንስ 6 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "Account info. sent successfully": "የአካውንት ቁጥር በተሳካ ሁኔታ ተልኳል",
          "Account Verified Successfully": "አካውንትዎ በተሳካ ሁኔታ ተረጋግጧል",
          "Complete all the fields below": "ከታች ያሉትን ሁሉንም መረጃዎች ያጠናቅቁ",
          "Bank Info.": "አካውንት መረጃ",
          "Account Number": "አካውንት ቁጥር",
          "Submit": "አስገባ",
          "OTP": "OTP",
          "Add": "አክል",
          "Please enter a valid name (letters and spaces only)":
              "እባክዎ ትክክለኛ ስም ያስገቡ (ፊደሎች እና ክፍተቶች ብቻ)",
          "Name must be at least 2 characters long": "ስም ቢያንስ 2 ፊድላት መሆን አለበት",
          "This field must be at least 2 characters long":
              "ይህ መስክ ቢያንስ የ2 ፊደላት ርዝመት ሊኖረው ይገባል።",
          "Personal info. sent successfully": "የግል መረጃ በተሳካ ሁኔታ ተልኳል።",
          "First Name": "ስም",
          "Last Name": "የአባት ስም",
          "Gender": "ጾታ",
          "Male": "ወንድ",
          "Female": "ሴት",
          "Id. Type": "መታወቂያ ዓይነት",
          "Driver's License": "የመንጃ ፍቃድ",
          "Passport": "ፓስፖርት",
          "National ID": "ብሔራዊ መታወቂያ",
          "Date of Birth": "የትውልድ ቀን",
          "Education level": "የትምህርት ደረጃ",
          "Primary": "መጀመሪያ ደረጃ",
          "Secondary": "ሁለተኛ ደረጃ",
          "BSc.": "ዲግሪ",
          "MSc.": "ማስተርስ",
          "ID. No.": "የመታወቂያ ቁጥር",
          "Marital Status": "የትዳር ሁኔታ",
          "Single": "ያላገባ",
          "Married": "ባለትዳር",
          "Divorced": "የተፋታ",
          "Widowed": "የሞተበት",
          "Spouse info.": "የትዳር አጋር መረጃ",
          "This field must contain only numbers": "ይህ መስክ ቁጥሮችን ብቻ መያዝ አለበት",
          "Altenative contact person": "የተያዥ ሰው መረጃ",
          "Residential Info.": "የመኖሪያ ቤት መረጃ",
          "Region/ District": "ክልል/ ከተማ",
          "Zone/ Subcity": "ዞን/ ክፍለ ከተማ",
          "Woreda": "ወረዳ",
          "Kebele": "ቀበሌ",
          "Re-Submit": "እንደገና አስገባ",
          "Business info. sent successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተልኳል",
          "Business info fetched successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተገኝቷል",
          "Business Name": "የንግድ ስም",
          "Website url (optional)": "ድህረገፅ (አማራጭ)",
          "Tin No.": "ቲን ቁጥር",
          "Business Type": "የንግድ ዓይነት",
          "Small Business Trade": "አነስተኛ የንግድ ልውውጥ",
          "Manufacturing": "ማምረት",
          "Agriculture": "ግብርና",
          "Transport": "መጓጓዣ",
          "Hospitality": "እንግዳ ተቀባይነት",
          "Halal Tourism": "ሃላል ቱሪዝም",
          "Technology": "ቴክኖሎጂ",
          "Building and Construction": "ግንባታ",
          "Education": "ትምህርት",
          "Other": "ሌላ",
          "Year of Establishment": "የተቋቋመበት ዓመት",
          "Ownership": "ባለቤትነት",
          "Sole": "የግል",
          "Partnership": "አጋርነት",
          "PLC": "ኃ.የተ.የግ.ማ",
          "Cooperative": "ህብረት",
          "Finance Source": "የፋይናንስ ምንጭ",
          "Own": "የራስ",
          "Family": "ቤተሰብ",
          "Fund": "ፈንድ",
          "Loan": "ብድር",
          "Business Level": "የንግድ ደረጃ",
          "Startup": "ጀማሪ",
          "Growing": "በማደግ ላይ",
          "Advanced": "የላቀ",
          "Starting Capital": "የመጀመሪያ ካፒታል",
          "Current Capital": "የአሁኑ ካፒታል",
          "Starting Employee No.": "የመጀመሪያ ሰራተኛ ቁጥር",
          "Current Employee No.": "የአሁኑ ሰራተኛ ቁጥር",
          "Annual Income(ETB)": "ዓመታዊ ገቢ (ብር)",
          "Business Address Info.": "የንግድ አድራሻ መረጃ",
          "Please upload at least one image.": "እባክዎ ቢያንስ አንድ ምስል ይላኩ።",
          "Images sent successfully!": "ምስሎች በተሳካ ሁኔታ ተልኳል!",
          "Upload the following files": "ከታች ያሉትን ምስሎች ያክሉ",
          "Personal and Business Info.": "የግል እና የንግድ መረጃ",
          "Renewed Id.": "የታደሰ መታወቂያ",
          "Renewed Id.(Sent)": "የታደሰ መታወቂያ(ተልኳል)",
          "Renewed Trade License": "የታደሰ የንግድ ፍቃድ",
          "Renewed Trade License(Sent)": "የታደሰ የንግድ ፍቃድ(ተልኳል)",
          "Commercial Registration Certificate": "የንግድ ምዝገባ የምስክር ወረቀት",
          "Commercial Registration Certificate(Sent)":
              "የንግድ ምዝገባ የምስክር ወረቀት(ተልኳል)",
          "TIN No. (Applicant's)": "ቲን ቁጥር (የአመልካች)",
          "TIN No. (Applicant's)(Sent)": "ቲን ቁጥር (የአመልካች)(ተልኳል)",
          "Selected: ": "ተመርጧል: ",
          ///////////////////////business partner screen////////////////////////
          "Business Partner's Phone Number": "የንግድ አጋር ስልክ ቁጥር",
          "Verify Partner": "የአጋር ማንነት ያረጋግጡ",
          "Partners Name": "የአጋር ስም",
          "Partne's Phone Number": "የአጋር ስልክ ቁጥር",
          "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions":
              "የንግድ አጋርዎ ያልተመዘገቡ ከሆነ በሚከተለው ሊንክ ወደ መድረኩ እንዲቀላቀሉ መጋበዝ ይችላሉ ወይም ሁሉንም KYC በመወከል የታችኛውን ቁልፍ በመጫን ወደ መድረኩ እንዲቀላቀሉ እና የብድር ጊዜውን እና ቅድመ ሁኔታዎችን እንዲቀበሉ ማድረግ ይችላሉ ",
          "Add the phone number of the person to be registered":
              "የሚመዘገበውን ሰው ስልክ ቁጥር አስገቡ",
          "Close": "ዝጋ",
          "Register your Partner": "አጋርዎን ይመዝግቡ",
          "Business Partners": "የንግድ አጋርዎች",
          "No Business Partners Found, Press the + button to add":
              "ምንም የንግድ አጋሮች አልተገኙም፣ ለመጨመር የ+ ቁልፍን ተጫን",
          ////////////////////////////provider loan list screen////////////////////////
          "Provider Loan Lists": "የአቅራቢ ብድር ዝርዝሮች",
          "Fill a Form": "ቅጽ ይሙሉ",
          "New": "አዲስ",
          "All": "ሁሉም",
          "Approved": "የጸደቀ",
          "The loan application is pending approval from the customer":
              "የብድር ማመልከቻው ከደንበኛው ፈቃድ በመጠባበቅ ላይ ነው።",
          "The loan application is under review by the Bank officers":
              "የብድር ማመልከቻው በባንኩ ኃላፊዎች እየተገመገመ ነው።",
          "The loan application is rejected": "የብድር ማመልከቻ ውድቅ ተደርጓል",
          "The loan application is under taking": "የብድር ማመልከቻው በመቀበል ላይ ነው።",
          "Agreements Accepted": "ስምምነቶች ተቀብለዋል",
          "The loan application is now closed.": "የብድር ማመልከቻው አሁን ተዘግቷል።",
          "There are no loans found": "ምንም ብድሮች አልተገኙም",
          "Name": "ስም",
          "Desc.": "ገለጻ",
          "Qnt.": "ብዛት",
          "Price": "ዋጋ",
          "Remove Product": "ምርቱን ያስወግዱ",
          "Are you sure you want to remove ": "እርግጠኛ ነዎት ማስወገድ ይፈልጋሉ ",
          "Cancel": "ሰርዝ",
          "Remove": "አስወግድ",
          "Unit of measurement": "የመለኪያ ክፍል",
          "Description": "መግለጫ",
          "Quantity": "ብዛት",
          "Under Review": "በመገመገመ ላይ",
          "Product Owner Form": "የምርት ባለቤት መረጃ ቅጽ",
          "Please enter the individual price for each product":
              "እባክዎ በባዶው ቦታው ላይ የአንዱን የእቃ ዋጋ ያስገቡ",
          "Total Price: ": "ጠቅላላ ዋጋ: ",
          "Price Expiration Date": "ይህ ዋጋ የሚያበቃበት ቀን",
          "Please select a price expiration date": "እባክዎ ይህ ዋጋ የሚያበቃበት ቀን ይምረጡ",
          "Please fill in all product prices":
              "እባክዎ በባዶው ቦታው ላይ የሁሉንም የእቃ ዋጋ ያስገቡ",
          "Confirm Submit": "ማስገቢያ ማረጋገጫ",
          "Confirm Reject": "አልቀበልም ማረጋገጫ",
          "Are you sure you want to submit this request?":
              "እርግጠኛ ነዎት እነዚህን ዋጋዎች ማስገባት ይፈልጋሉ?",
          "Are you sure you want to reject this request?":
              "እርግጠኛ ነዎት ይህን ጥያቄ አይቀበሉም?",
          ////////////////////////////Loan List Screen//////////////////////////
          "Loan Requests": "የብድር ጥያቄዎች",
          "Congratulations!": "እንኳን ደስ አሎት!",
          "Your loan has been approved!": "ብድርዎ ጸድቋል!",
          "Your loan application has been successfully approved. You will be contacted shortly by our team for the next steps.":
              "የብድር ማመልከቻዎ በተሳካ ሁኔታ ጸድቋል። ለቀጣይ እርምጃዎች ከቡድናችን መልእክት በቅርቡ ይደርሶታል",
          "ETB ": "ብር ",
          "Back to Home": "ወደ መግቢያው ይመለሱ",
          "No products found": "ምንም ምርቶች አልተገኙም",
          "Loan Approval Status": "የብድር ማመልከቻ ሁኔታ",
          "This loan application has been approved by the product owner and now it is under review by the bank's officials. The bank will put it's benefits to the product and will let you know the final offer soon.":
              "ይህ የብድር ማመልከቻ በምርቱ ባለቤት የተፈቀደ ሲሆን አሁን በባንኩ ኃላፊዎች እየተገመገመ ነው። ባንኩ ጥቅሞቹን ለምርቱ ያስቀምጣል እና የመጨረሻውን ቅናሽ በቅርቡ ያሳውቅዎታል።",
          "Total Price": "ጠቅላላ ዋጋ",
          "Confirmation": "ማረጋገጫ",
          "Are you sure you want to resubmit your new offer?":
              "እርግጠኛ ነዎት አዲሱን መረጃ እንደገና ማስገባት ይፈልጋሉ?",
          "Are you sure you want to reject the offer?":
              "እርግጠኛ ነህ ዋጋውን አለመቀበል ትፈልጋለህ?",
          "Accept Offer": "ዋጋውን ተቀበል",
          "Resubmit Offer": "አዲሱን መረጃ ላክ",
          "Reject Offer": "ዋጋውን አልቀበልም",
          "Murabaha Agreement": "የሙራባሃ ስምምነት",
          "This loan application has been approved by the product owner and the bank officials.":
              "ይህ የብድር ማመልከቻ በምርቱ ባለቤት እና በባንኩ ኃላፊዎች ጸድቋል።",
          "The total price as the owner gives is ": "በባለቤቱ የተቀመጠው አጠቃላይ ዋጋ  ",
          " in ": " በ ",
          "repayment duration.": "የመክፈያ ጊዜ።",
          ", then the bank has added its benefits to the product price, making the final offer ":
              ", ከዚያም ባንኩ ጥቅሞቹን በምርቱ ዋጋ ላይ ይጨምራል, ከዚያም የመጨረሻውን ዋጋ ይልካል ",
          "Now, you must accept this offer and pick your product from the owner as soon as possible.":
              "አሁን፣ ይህንን አቅርቦት መቀበል እና በተቻለ ፍጥነት ምርትዎን ከባለቤቱ ይውሰዱ።",
          "Pick your product": "ምርትዎን ይውሰዱ",
          "Are you sure you are ready to pick your product?":
              "እርግጠኛ ነዎት ምርትዎን ለመቀበል ዝግጁ ነዎት?",
          "Please ensure you are at the product pickup location and ready to sign the Murabaha agreement.":
              "እባክህ ምርቱን በሚወስዱበት ቦታ ላይ መሆንዎን እና የሙራባሃ ስምምነትን ለመፈረም ዝግጁ መሆንዎን ያረጋግጡ።",
          "Not Ready": "ዝግጁ አይደለሁም",
          "I'm Ready": "ዝግጁ ነኝ",
          "Promise to Purchase Agreement": "የግዢ ስምምነት ቃል መግቢያ",
          "Agree": "ተቀበል",
          "PDF saved": "ፒዲኤፍ ተቀምጧል",
          "Failed to download PDF": "ፒዲኤፍ ማውረድ አልተሳካም።",
          "Failed to load PDF": "ፒዲኤፍ መጫን አልተሳካም።",
          "Reject": "አልቀበልም",
          "Accept": "ተቀበል",
          "Duration of Financing": "የፋይናንስ ቆይታ",
          "Total Murabaha Price": "ጠቅላላ የሙራባሃ ዋጋ",
          "Mark up": "ትርፍ",
          "Purchase Cost": "የግዢ ዋጋ",
          "Processing Fees": "የማስኬጃ ክፍያዎች",
          "Product Name: ": "የምርት ስም: ",
          "Unit Price: ": "የአንዱ ዋጋ: ",
          "Quantity: ": "ብዛት: ",
          "Total: ": "ጠቅላላ: ",
          "Edit Quantity": "ብዛትን ቀይር",
          "Delete Product": "ምርትን ይሰርዙ",
          "Are you sure you want to delete ": "እርግጠኛ ነዎት ይህን መሰረዝ ይፈልጋሉ ",
          "Save": "አስቀምጥ",
          "Delete": "ሰርዝ",
          "The loan application is pending approval from the merchant":
              "የብድር ማመልከቻው ከነጋዴው ፈቃድ በመጠባበቅ ላይ ነው።",
          "The loan application is approved and will be fulfilled once the product owner confirms it.":
              "የብድር ማመልከቻው ጸድቋል እና የምርት ባለቤቱ ካረጋገጠ በኋላ ይሟላል።",
        },
        'or_ET': {
          "Michu Mizan": "Michuu Mizaan",
          "Welcome to": "Anaa Dhufu",
          "English": "Afaan Oromoo",
          "Login": "Seenii",
          "Signup": "Galmaa'i",
          "Forgot Password?": "የይለፍ ቃል ረሱ?",
          "Don't have an account?  ": "መለያ የለህም?",
          "Phone Number": "ስልክ ቁጥር",
          "Password": "የይለፍ ቃል",
          "Choose Language": "ቋንቋ ይምረጡ",
          "Logged in successfully": "በተሳካ ሁኔታ ገብቷል",
          "Invalid phone number format": "ልክ ያልሆነ የስልክ ቁጥር",
          "Phone number is required": "ስልክ ቁጥር ያስፈልጋል",
          "Password must be at least 6 characters":
              "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት",
          "Password is required": "የይለፍ ቃል ያስፈልጋል",
          ////////////////////////login screen////////////////////////
          "Enter your details below to create your account and get started":
              "መለያዎን ለመፍጠር እና ለመጀመር ዝርዝሮችዎን ከዚህ በታች ያስገቡ",
          "Full Name": "ሙሉ ስም",
          "Full name is required": "ሙሉ ስም ያስፈልጋል",
          "Confirm Password": "የይለፍ ቃል ያረጋግጡ",
          "Confirm password is required": "የይለፍ ቃል ማረጋግጫ ያስፈልጋል",
          "Password does not match": "የይለፍ ቃል አይዛመድም",
          "Do you have an account?  ": "መለያ የለህም?  ",
          ////////////////////////////forgot password screen////////////////////////
          "Forgot Password": "የይለፍ ቃል ረሱ",
          "Send OTP": "OTP ላክ",
          "Enter OTP": "OTP አስገባ",
          "We have sent an OTP to ": "OTP ልከናል ",
          "Password changed successfuly": "የይለፍ ቃል በተሳካ ሁኔታ ተቀይሯል",
          ///////////////////////////home screen////////////////////////
          "Hello ": "ሰላም ",
          "Good Morning!": "እንደምን አነጉ!",
          "Good Afternoon!": "እንደምን አረፈዱ!",
          "Good Evening!": "አንደምን አመሹ!",
          "Something went wrong": "የሆነ ችግር ተፈጥሯል",
          "Very Poor": "በጣም ትንሽ",
          "Poor": "ትንሽ",
          "Average": "አማካይ",
          "Good": "ጥሩ",
          "Excellent": "እጅግ በጣም ጥሩ",
          "Your Credit Score: ": "የክሬዲት ነጥብዎ፡- ",
          "Complete your KYC to achieve a good credit score. A verified KYC helps improve your financial profile!":
              "ጥሩ የብድር ነጥብ ለማግኘት የእርስዎን KYC ያጠናቅቁ። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Your KYC is verified. A verified KYC helps improve your financial profile!":
              "የእርስዎ KYC የተረጋገጠ ነጥብ ነው። የተረጋገጠ KYC የእርስዎን የፋይናንስ መገለጫ ለማሻሻል ይረዳል!",
          "Loan App": "ብድር ማመልከቻ",

          "Please fill KYC before going to loan applications.":
              "ወደ ብድር ማመልከቻዎች ከመሄድዎ በፊት እባክዎን KYC ይሙሉ",
          "Verify": "ማንነትዎን ያረጋግጡ",
          "Provider": "አቅራቢ",
          "Provider Form": "የአቅራቢ ቅጽ",
          "Murabaha": "ሙራባሃ",
          "Musharaka": "ሙሻረካ",
          "Mudarabah": "ሙዳረባ",
          "Murabaha at Coop Bank is a Sharia-compliant financing product where the bank buys goods for customers and resells them at a disclosed profit, allowing interest-free financing in line with Islamic principles.":
              "ሙራባሃ በኮፕ ባንክ ሸሪዓን የሚያከብር የፋይናንስ ምርት ሲሆን ባንኩ ለደንበኞች እቃዎችን ገዝቶ በተገለጸለት ትርፍ እንደገና የሚሸጥበት ሲሆን ይህም ከወለድ ነፃ የሆነ ፋይናንስ በኢስላማዊ መርሆች መሰረት ይፈቅዳል።",
          "Musharaka is a partnership-based financing method where both the bank and the customer contribute capital to a joint venture or project, sharing profits according to a pre-agreed ratio while losses are shared in proportion to their respective capital contributions, adhering to Sharia principles.":
              "ሙሻራካ በሽርክና ላይ የተመሰረተ የፋይናንስ ዘዴ ሲሆን ባንኩም ሆነ ደንበኛው ለጋራ ወይም ለፕሮጀክት ካፒታል የሚያዋጡበት፣ ቀድሞ በተስማማው ጥምርታ መሠረት ትርፍ የሚካፈሉበት፣ ኪሳራው ደግሞ የሸሪዓን መርሆች በማክበር ከካፒታል መዋጮቸው ጋር በተመጣጣኝ መጠን የሚካፈሉበት ነው።",
          "Mudaraba is a profit-sharing agreement where one party (the bank) provides the capital, and the other party (the entrepreneur) manages the business, with profits shared as per a pre-agreed ratio, and losses borne solely by the capital provider in line with Islamic financing norms.":
              "ሙዳርባ የትርፍ መጋራት ስምምነት አንዱ አካል (ባንኩ) ካፒታል ሲያቀርብ ሌላኛው አካል (ሥራ ፈጣሪው) ሥራውን የሚያስተዳድርበት፣ ቀደም ሲል በተስማማው ጥምርታ መሠረት ትርፍ የሚጋራበት እና በካፒታል አቅራቢው ብቻ የሚደርሰው ኪሳራ ነው። ከእስላማዊ የፋይናንስ ደንቦች ጋር ይጣጣማል።",
          "Collapse": "ሰብስብ",
          "Expand": "ዘርጋ",
          //////////////////////////finances Screen////////////////////////
          "Finances": "ፋይናንስ",
          "Loan Request": "የብድር መጠየቂያ",
          "Loan Repay": "የብድር ክፍያ",
          "Loan Status": "የብድር ሁኔታ",
          "Add Provider": "አቅራቢን ያክሉ",
          "Overall loan History": "አጠቃላይ የብድር ታሪክ",
          "No active loans available": "ምንም ገቢር ብድሮች የሉም",
          ///////////////////////////////profile screen////////////////////////////
          "KYC Completed": "የተጠናቀቀ KYC",
          "Complete KYC": "KYC ያጠናቅቁ",
          "Personal Info.": "የግል መረጃ",
          "Business Info.": "የንግድ መረጃ",
          "Images Info.": "የምስሎች መረጃ",
          "Account Info.": "የመለያ መረጃ",
          "Add Business Partner": "የንግድ አጋር ያክሉ",
          "Completed Loans": "የተጠናቀቁ ብድሮች",
          "Pending Loans": "በመጠባበቅ ላይ ያሉ ብድሮች",
          "Failed Loans": "ያልተሳኩ ብድሮች",
          "Click Here": "እዚህ ይሙሉ",
          "If you are here as a product seller and wanted to fill a form or check status please click the button bellow":
              "እዚህ እንደ ምርት ሻጭ ከሆኑ እና ፎርም መሙላት ከፈለጉ ወይም የብድር ሁኔታን ለማረጋገጥ እባክዎ ከታች ያለውን ቁልፍ ይጫኑ",
          "Home": "መነሻ",
          "Profile": "መገለጫ",
          "Confirm Logout": "መውጣት ያረጋግጡ",
          "Do you want to Logout?": "መውጣት ይፈልጋሉ?",
          "No": "አይ",
          "Yes": "አዎ",
          "Error logging out": "መውጣት ላይ ስህተት ተፈጥሯል",
          ///////////////////////////loan application screen////////////////////////
          "This field is required": "ይህ መረጃ ያስፈልጋል",
          "Please enter a quantity": "እባክዎ መጠን ያስገቡ",
          "Please enter a valid number": "እባክዎ ትክክለኛ ቁጥር ያስገቡ",
          "Apply for Murabaha Loan": "ለሙራባሃ ብድር ያመልክቱ",
          "No providers found": "ምንም አቅራቢዎች አልተገኙም",
          "Product request sent successfully": "የምርት ጥያቄ በተሳካ ሁኔታ ተልኳል",
          "Name of Product": "የምርት ስም",
          "Quantity of Asset": "የንብረት ብዛት",
          "Product Desc.": "የምርት መግለጫ",
          "Unit of Measurement": "የመለኪያ ክፍል",
          "Sector": "ዘርፍ",
          "Repayment Plan": "የመክፈያ እቅድ",
          "Please add products first": "እባክዎ መጀመሪያ ምርቶችን ያክሉ",
          "Apply Loan": "ብድር ያመልክቱ",
          ////////////////////////////////////kyc screen////////////////////////////
          "Bank Link": "አካውንት አገናኝ",
          "Pers. Info.": "የግል መረጃ",
          "Bus. Info.": "የንግድ መረጃ",
          "Upload Image": "ምስሎችን ያክሉ",
          "Rejected": "አልተሳካም",
          "You can resubmit your KYC info. and we'll review it ASAP.":
              "የእርስዎን የKYC መረጃ እንደገና ማስገባት ይችላሉ። እና በፍጥነት እንገመግመዋለን።",
          "OK": "እሺ",
          "Your KYC submission is under review.": "የእርስዎ KYC መረጃ በግምገማ ላይ ነው።",
          "Pending": "በመጠባበቅ ላይ",
          "We will notify you once the review is complete.":
              "ግምገማው እንደተጠናቀቀ እናሳውቅዎታለን።",
          "Success": "ተሳክቷል",
          "Your KYC submission has been approved.": "የKYC መረጃዎ ጸድቋል።",
          "Thank you for completing your KYC process.":
              "የKYC ሂደትዎን ስላጠናቀቁ እናመሰግናለን።",
          "This field must be at least 13 digits long":
              "ይህ መስክ ቢያንስ 13 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "This field must be at least 6 digits long":
              "ይህ መስክ ቢያንስ 6 ቁጥሮች ርዝመት ሊኖረው ይገባል",
          "Account info. sent successfully": "የአካውንት ቁጥር በተሳካ ሁኔታ ተልኳል",
          "Account Verified Successfully": "አካውንትዎ በተሳካ ሁኔታ ተረጋግጧል",
          "Complete all the fields below": "ከታች ያሉትን ሁሉንም መረጃዎች ያጠናቅቁ",
          "Bank Info.": "አካውንት መረጃ",
          "Account Number": "አካውንት ቁጥር",
          "Submit": "አስገባ",
          "OTP": "OTP",
          "Add": "አክል",
          "Please enter a valid name (letters and spaces only)":
              "እባክዎ ትክክለኛ ስም ያስገቡ (ፊደሎች እና ክፍተቶች ብቻ)",
          "Name must be at least 2 characters long": "ስም ቢያንስ 2 ፊድላት መሆን አለበት",
          "This field must be at least 2 characters long":
              "ይህ መስክ ቢያንስ የ2 ፊደላት ርዝመት ሊኖረው ይገባል።",
          "Personal info. sent successfully": "የግል መረጃ በተሳካ ሁኔታ ተልኳል።",
          "First Name": "ስም",
          "Last Name": "የአባት ስም",
          "Gender": "ጾታ",
          "Male": "ወንድ",
          "Female": "ሴት",
          "Id. Type": "መታወቂያ ዓይነት",
          "Driver's License": "የመንጃ ፍቃድ",
          "Passport": "ፓስፖርት",
          "National ID": "ብሔራዊ መታወቂያ",
          "Date of Birth": "የትውልድ ቀን",
          "Education level": "የትምህርት ደረጃ",
          "Primary": "መጀመሪያ ደረጃ",
          "Secondary": "ሁለተኛ ደረጃ",
          "BSc.": "ዲግሪ",
          "MSc.": "ማስተርስ",
          "ID. No.": "የመታወቂያ ቁጥር",
          "Marital Status": "የትዳር ሁኔታ",
          "Single": "ያላገባ",
          "Married": "ባለትዳር",
          "Divorced": "የተፋታ",
          "Widowed": "የሞተበት",
          "Spouse info.": "የትዳር አጋር መረጃ",
          "This field must contain only numbers": "ይህ መስክ ቁጥሮችን ብቻ መያዝ አለበት",
          "Altenative contact person": "የተያዥ ሰው መረጃ",
          "Residential Info.": "የመኖሪያ ቤት መረጃ",
          "Region/ District": "ክልል/ ከተማ",
          "Zone/ Subcity": "ዞን/ ክፍለ ከተማ",
          "Woreda": "ወረዳ",
          "Kebele": "ቀበሌ",
          "Re-Submit": "እንደገና አስገባ",
          "Business info. sent successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተልኳል",
          "Business info fetched successfully": "የንግድ መረጃ በተሳካ ሁኔታ ተገኝቷል",
          "Business Name": "የንግድ ስም",
          "Website url (optional)": "ድህረገፅ (አማራጭ)",
          "Tin No.": "ቲን ቁጥር",
          "Business Type": "የንግድ ዓይነት",
          "Small Business Trade": "አነስተኛ የንግድ ልውውጥ",
          "Manufacturing": "ማምረት",
          "Agriculture": "ግብርና",
          "Transport": "መጓጓዣ",
          "Hospitality": "እንግዳ ተቀባይነት",
          "Halal Tourism": "ሃላል ቱሪዝም",
          "Technology": "ቴክኖሎጂ",
          "Building and Construction": "ግንባታ",
          "Education": "ትምህርት",
          "Other": "ሌላ",
          "Year of Establishment": "የተቋቋመበት ዓመት",
          "Ownership": "ባለቤትነት",
          "Sole": "የግል",
          "Partnership": "አጋርነት",
          "PLC": "ኃ.የተ.የግ.ማ",
          "Cooperative": "ህብረት",
          "Finance Source": "የፋይናንስ ምንጭ",
          "Own": "የራስ",
          "Family": "ቤተሰብ",
          "Fund": "ፈንድ",
          "Loan": "ብድር",
          "Business Level": "የንግድ ደረጃ",
          "Startup": "ጀማሪ",
          "Growing": "በማደግ ላይ",
          "Advanced": "የላቀ",
          "Starting Capital": "የመጀመሪያ ካፒታል",
          "Current Capital": "የአሁኑ ካፒታል",
          "Starting Employee No.": "የመጀመሪያ ሰራተኛ ቁጥር",
          "Current Employee No.": "የአሁኑ ሰራተኛ ቁጥር",
          "Annual Income(ETB)": "ዓመታዊ ገቢ (ብር)",
          "Business Address Info.": "የንግድ አድራሻ መረጃ",
          "Please upload at least one image.": "እባክዎ ቢያንስ አንድ ምስል ይላኩ።",
          "Images sent successfully!": "ምስሎች በተሳካ ሁኔታ ተልኳል!",
          "Upload the following files": "ከታች ያሉትን ምስሎች ያክሉ",
          "Personal and Business Info.": "የግል እና የንግድ መረጃ",
          "Renewed Id.": "የታደሰ መታወቂያ",
          "Renewed Id.(Sent)": "የታደሰ መታወቂያ(ተልኳል)",
          "Renewed Trade License": "የታደሰ የንግድ ፍቃድ",
          "Renewed Trade License(Sent)": "የታደሰ የንግድ ፍቃድ(ተልኳል)",
          "Commercial Registration Certificate": "የንግድ ምዝገባ የምስክር ወረቀት",
          "Commercial Registration Certificate(Sent)":
              "የንግድ ምዝገባ የምስክር ወረቀት(ተልኳል)",
          "TIN No. (Applicant's)": "ቲን ቁጥር (የአመልካች)",
          "TIN No. (Applicant's)(Sent)": "ቲን ቁጥር (የአመልካች)(ተልኳል)",
          "Selected: ": "ተመርጧል: ",
          ///////////////////////business partner screen////////////////////////
          "Business Partner's Phone Number": "የንግድ አጋር ስልክ ቁጥር",
          "Verify Partner": "የአጋር ማንነት ያረጋግጡ",
          "Partners Name": "የአጋር ስም",
          "Partne's Phone Number": "የአጋር ስልክ ቁጥር",
          "If your business partner is not registered you can invite them to join the platform by the following link or you can fill all the KYC on behalf of them by clicking the bottom button and let them join the platform and just accept the loan term and conditions":
              "የንግድ አጋርዎ ያልተመዘገቡ ከሆነ በሚከተለው ሊንክ ወደ መድረኩ እንዲቀላቀሉ መጋበዝ ይችላሉ ወይም ሁሉንም KYC በመወከል የታችኛውን ቁልፍ በመጫን ወደ መድረኩ እንዲቀላቀሉ እና የብድር ጊዜውን እና ቅድመ ሁኔታዎችን እንዲቀበሉ ማድረግ ይችላሉ ",
          "Add the phone number of the person to be registered":
              "የሚመዘገበውን ሰው ስልክ ቁጥር አስገቡ",
          "Close": "ዝጋ",
          "Register your Partner": "አጋርዎን ይመዝግቡ",
          "Business Partners": "የንግድ አጋርዎች",
          "No Business Partners Found, Press the + button to add":
              "ምንም የንግድ አጋሮች አልተገኙም፣ ለመጨመር የ+ ቁልፍን ተጫን",
          ////////////////////////////provider loan list screen////////////////////////
          "Provider Loan Lists": "የአቅራቢ ብድር ዝርዝሮች",
          "Fill a Form": "ቅጽ ይሙሉ",
          "New": "አዲስ",
          "All": "ሁሉም",
          "Approved": "የጸደቀ",
          "The loan application is pending approval from the customer":
              "የብድር ማመልከቻው ከደንበኛው ፈቃድ በመጠባበቅ ላይ ነው።",
          "The loan application is under review by the Bank officers":
              "የብድር ማመልከቻው በባንኩ ኃላፊዎች እየተገመገመ ነው።",
          "The loan application is rejected": "የብድር ማመልከቻ ውድቅ ተደርጓል",
          "The loan application is under taking": "የብድር ማመልከቻው በመቀበል ላይ ነው።",
          "Agreements Accepted": "ስምምነቶች ተቀብለዋል",
          "The loan application is now closed.": "የብድር ማመልከቻው አሁን ተዘግቷል።",
          "There are no loans found": "ምንም ብድሮች አልተገኙም",
          "Name": "ስም",
          "Desc.": "ገለጻ",
          "Qnt.": "ብዛት",
          "Price": "ዋጋ",
          "Remove Product": "ምርቱን ያስወግዱ",
          "Are you sure you want to remove ": "እርግጠኛ ነዎት ማስወገድ ይፈልጋሉ ",
          "Cancel": "ሰርዝ",
          "Remove": "አስወግድ",
          "Unit of measurement": "የመለኪያ ክፍል",
          "Description": "መግለጫ",
          "Quantity": "ብዛት",
          "Under Review": "በመገመገመ ላይ",
          "Product Owner Form": "የምርት ባለቤት መረጃ ቅጽ",
          ////////////////////////////Loan List Screen//////////////////////////
          "Loan Requests": "የብድር ጥያቄዎች",
          "Congratulations!": "እንኳን ደስ አሎት!",
          "Your loan has been approved!": "ብድርዎ ጸድቋል!",
          "Your loan application has been successfully approved. You will be contacted shortly by our team for the next steps.":
              "የብድር ማመልከቻዎ በተሳካ ሁኔታ ጸድቋል። ለቀጣይ እርምጃዎች ከቡድናችን መልእክት በቅርቡ ይደርሶታል",
          "ETB ": "ብር ",
          "Back to Home": "ወደ መግቢያው ይመለሱ",
          "No products found": "ምንም ምርቶች አልተገኙም",
          "Loan Approval Status": "የብድር ማመልከቻ ሁኔታ",
          "This loan application has been approved by the product owner and now it is under review by the bank's officials. The bank will put it's benefits to the product and will let you know the final offer soon.":
              "ይህ የብድር ማመልከቻ በምርቱ ባለቤት የተፈቀደ ሲሆን አሁን በባንኩ ኃላፊዎች እየተገመገመ ነው። ባንኩ ጥቅሞቹን ለምርቱ ያስቀምጣል እና የመጨረሻውን ቅናሽ በቅርቡ ያሳውቅዎታል።",
          "Total Price": "ጠቅላላ ዋጋ",
          "Confirmation": "ማረጋገጫ",
          "Are you sure you want to resubmit your new offer?":
              "እርግጠኛ ነዎት አዲሱን መረጃ እንደገና ማስገባት ይፈልጋሉ?",
          "Are you sure you want to reject the offer?":
              "እርግጠኛ ነህ ዋጋውን አለመቀበል ትፈልጋለህ?",
          "Accept Offer": "ዋጋውን ተቀበል",
          "Resubmit Offer": "አዲሱን መረጃ ላክ",
          "Reject Offer": "ዋጋውን አልቀበልም",
          "Murabaha Agreement": "የሙራባሃ ስምምነት",
          "This loan application has been approved by the product owner and the bank officials.":
              "ይህ የብድር ማመልከቻ በምርቱ ባለቤት እና በባንኩ ኃላፊዎች ጸድቋል።",
          "The total price as the owner gives is ": "በባለቤቱ የተቀመጠው አጠቃላይ ዋጋ  ",
          " in ": " በ ",
          "repayment duration.": "የመክፈያ ጊዜ።",
          ", then the bank has added its benefits to the product price, making the final offer ":
              ", ከዚያም ባንኩ ጥቅሞቹን በምርቱ ዋጋ ላይ ይጨምራል, ከዚያም የመጨረሻውን ዋጋ ይልካል ",
          "Now, you must accept this offer and pick your product from the owner as soon as possible.":
              "አሁን፣ ይህንን አቅርቦት መቀበል እና በተቻለ ፍጥነት ምርትዎን ከባለቤቱ ይውሰዱ።",
          "Pick your product": "ምርትዎን ይውሰዱ",
          "Are you sure you are ready to pick your product?":
              "እርግጠኛ ነዎት ምርትዎን ለመቀበል ዝግጁ ነዎት?",
          "Please ensure you are at the product pickup location and ready to sign the Murabaha agreement.":
              "እባክህ ምርቱን በሚወስዱበት ቦታ ላይ መሆንዎን እና የሙራባሃ ስምምነትን ለመፈረም ዝግጁ መሆንዎን ያረጋግጡ።",
          "Not Ready": "ዝግጁ አይደለሁም",
          "I'm Ready": "ዝግጁ ነኝ",
          "Promise to Purchase Agreement": "የግዢ ስምምነት ቃል መግቢያ",
          "Agree": "ተቀበል",
          "PDF saved": "ፒዲኤፍ ተቀምጧል",
          "Failed to download PDF": "ፒዲኤፍ ማውረድ አልተሳካም።",
          "Failed to load PDF": "ፒዲኤፍ መጫን አልተሳካም።",
          "Reject": "አልቀበልም",
          "Accept": "ተቀበል",
          "Duration of Financing": "የፋይናንስ ቆይታ",
          "Total Murabaha Price": "ጠቅላላ የሙራባሃ ዋጋ",
          "Mark up": "ትርፍ",
          "Purchase Cost": "የግዢ ዋጋ",
          "Processing Fees": "የማስኬጃ ክፍያዎች",
          "Product Name: ": "የምርት ስም: ",
          "Unit Price: ": "የአንዱ ዋጋ: ",
          "Quantity: ": "ብዛት: ",
          "Total: ": "ጠቅላላ: ",
          "Edit Quantity": "ብዛትን ቀይር",
          "Delete Product": "ምርትን ይሰርዙ",
          "Are you sure you want to delete ": "እርግጠኛ ነዎት ይህን መሰረዝ ይፈልጋሉ ",
          "Save": "አስቀምጥ",
          "Delete": "ሰርዝ",
          "The loan application is pending approval from the merchant":
              "የብድር ማመልከቻው ከነጋዴው ፈቃድ በመጠባበቅ ላይ ነው።",
          "The loan application is approved and will be fulfilled once the product owner confirms it.":
              "የብድር ማመልከቻው ጸድቋል እና የምርት ባለቤቱ ካረጋገጠ በኋላ ይሟላል።",
        }
      };
}
